### ISSUE TITLE
404 on https://www.laravel-enso.com/login

### ISSUE THREAD

**Issue by robbykrlos** [enso-ui/auth#4]
This is  a **bug | question**.

Hi,

I see there are some "404" UI Reponses (not actual http responses) on UI when doing:

1. Login on https://www.laravel-enso.com/login.
2. Open new tab.
3. Open again https://www.laravel-enso.com/login (like a existing bookmark).
4. Look at the tab titles - at some point 404 will be displayed.

Is this because once logged in, the route /login is no longer accessible by authenticated users, therefore 404 (only guests)?

or another:
1. Be sure you do not have a session opened (logout)
2. access https://www.laravel-enso.com/
3. A redirect will be made to /login
4. In the redirect process the tab will shortly display 404.

Is this normal?

![image](https://user-images.githubusercontent.com/16973022/113161603-371e5480-9247-11eb-9af0-9cb5badbed6b.png)

PS: initially I thought it's because of the missing favicon.png, which is missing from resources/images (Missing favicon.png (minor) https://github.com/laravel-enso/enso/issues/382)

Thank you,

**Comment by aocneanu** [comment]
>Is this because once logged in, the route /login is no longer accessible by authenticated users, therefore 404 (only guests)?

Yes

Actually we have `@enso-ui/ui/src/core/components/DocumentTitle.vue` which handles the page title at all times.

@vmcvlad I believe you also reported this, I cannot find the issue.

**Comment by aocneanu** [comment]
fixed with https://github.com/enso-ui/ui/commit/c84b3609d6afc50899c16ebded1ecd23e233ae61
