### ISSUE TITLE
Some modules still require @enso-ui/auth ^2.0 dependency

### ISSUE THREAD

**Issue by robbykrlos** [enso-ui/auth#8]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
There are stil dependencies requiring old version of `@enso-ui/auth`  -  `^2.0` in these packages:

- @enso-ui\bulma\node_modules\@enso-ui\ui\package.json
- @enso-ui\bulma\node_modules\@enso-ui\users\package.json
- @enso-ui\charts\node_modules\@enso-ui\ui\package.json
- @enso-ui\charts\node_modules\@enso-ui\users\package.json
- @enso-ui\discussions\node_modules\@enso-ui\ui\package.json
- @enso-ui\discussions\node_modules\@enso-ui\users\package.json
- @enso-ui\files\node_modules\@enso-ui\ui\package.json
- @enso-ui\files\node_modules\@enso-ui\users\package.json
- @enso-ui\permissions\node_modules\@enso-ui\ui\package.json
- @enso-ui\permissions\node_modules\@enso-ui\users\package.json

**Comment by aocneanu** [comment]
fixed a while ago
